# Dockerfile
FROM mongo:latest

# Optional: Add any custom configuration or files
# For example, copying a custom MongoDB configuration file
# COPY mongod.conf /etc/mongo/mongod.conf

# Set the default command
CMD ["mongod"]
