version: '3.9'

services:
  cassandra:
    image: cassandra-with-keyspace  # Use the custom image
    container_name: cassandra-node
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "TestCluster"
      CASSANDRA_NUM_TOKENS: 256
      MAX_HEAP_SIZE: "512M"
      HEAP_NEWSIZE: "100M"
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data:
